<img src="https://i.ibb.co/sFcTVM4/DALL-E-2023-12-28-17-48-36-Create-a-logo-using-the-simplified-design-featuring-a-sprout-and-an-upwar.png" width="100"/>

---
-  강의 및 추가 자료 링크
- 강의 링크: [Python 강의](#)

-  소셜 미디어 및 연락처
  - 저자 SNS: [instagram](https://www.instagram.com/ringo_data/?igsh=MTlrdW4xMzZvNTBtdw%3D%3D), [LinkedIn](https://www.linkedin.com/in/ringokwon/)
  - 이메일: ringo.data1@gmail.com

---

# Index
- 인덱스 (Index): 행을 구별하는 데 사용되는 고유한 식별자.

```python
df.set_index('col1', inplace = True) # index 지정
df.reset_index(inplace = True ) # 기본 정수 Index
```

In [15]:
# taxis
import seaborn as sns
df = sns.load_dataset('taxis')
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [16]:
df.set_index('pickup', inplace=True)
df.head()

,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
pickup,,,,,,,,,,,,,
2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [17]:
df.reset_index(inplace=True)
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

# Sort
- 특정 기준에 따라 순서대로 `나열`
- sort_value():특정 column 기준
```python
df.sort_values('col1', ascending = False, inplace = True )
```
  - ascending = False: 내림차순
  - ascending = True: 오름차순

- sort_index(): index 기준
```python
df.sort_index(inplace= True)
```

In [20]:
df.sort_values('distance', ascending=False).head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
5364,2019-03-17 16:59:17,2019-03-17 18:04:08,2,36.70,150.0,0.00,24.02,174.82,yellow,cash,JFK Airport,JFK Airport,Queens,Queens
4219,2019-03-08 20:07:54,2019-03-08 21:10:00,1,36.66,96.5,10.00,5.76,113.56,yellow,credit card,JFK Airport,NaN,Queens,NaN
4050,2019-03-13 14:05:19,2019-03-13 15:01:16,6,33.76,143.5,0.00,0.00,144.30,yellow,cash,LaGuardia Airport,NaN,Queens,NaN
5648,2019-03-19 14:21:35,2019-03-19 15:51:28,2,33.46,150.0,0.00,18.90,169.70,green,cash,East Flushing,NaN,Queens,NaN
2397,2019-03-21 18:56:59,2019-03-21 19:49:58,1,30.23,52.0,13.11,5.76,78.67,yellow,credit card,JFK Airport,Meatpacking/West Village West,Queens,Manhattan

In [21]:
df.sort_values('distance', ascending=False).reset_index().head()

,index,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,5364,2019-03-17 16:59:17,2019-03-17 18:04:08,2,36.70,150.0,0.00,24.02,174.82,yellow,cash,JFK Airport,JFK Airport,Queens,Queens
1,4219,2019-03-08 20:07:54,2019-03-08 21:10:00,1,36.66,96.5,10.00,5.76,113.56,yellow,credit card,JFK Airport,NaN,Queens,NaN
2,4050,2019-03-13 14:05:19,2019-03-13 15:01:16,6,33.76,143.5,0.00,0.00,144.30,yellow,cash,LaGuardia Airport,NaN,Queens,NaN
3,5648,2019-03-19 14:21:35,2019-03-19 15:51:28,2,33.46,150.0,0.00,18.90,169.70,green,cash,East Flushing,NaN,Queens,NaN
4,2397,2019-03-21 18:56:59,2019-03-21 19:49:58,1,30.23,52.0,13.11,5.76,78.67,yellow,credit card,JFK Airport,Meatpacking/West Village West,Queens,Manhattan

In [23]:
df.sort_values('distance', ascending=False, inplace=True)
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
5364,2019-03-17 16:59:17,2019-03-17 18:04:08,2,36.70,150.0,0.00,24.02,174.82,yellow,cash,JFK Airport,JFK Airport,Queens,Queens
4219,2019-03-08 20:07:54,2019-03-08 21:10:00,1,36.66,96.5,10.00,5.76,113.56,yellow,credit card,JFK Airport,NaN,Queens,NaN
4050,2019-03-13 14:05:19,2019-03-13 15:01:16,6,33.76,143.5,0.00,0.00,144.30,yellow,cash,LaGuardia Airport,NaN,Queens,NaN
5648,2019-03-19 14:21:35,2019-03-19 15:51:28,2,33.46,150.0,0.00,18.90,169.70,green,cash,East Flushing,NaN,Queens,NaN
2397,2019-03-21 18:56:59,2019-03-21 19:49:58,1,30.23,52.0,13.11,5.76,78.67,yellow,credit card,JFK Airport,Meatpacking/West Village West,Queens,Manhattan

In [24]:
# 이전에 reset_index()를 호출하지 않았기 때문에, 기존의 df index가 그대로 남아있음. 
df.sort_index().head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

# Exercise
- 일시정지 후 스스로 문제를 풀어보고 강의를 수강해 주세요

1. 문제: 아래는 상품 판매 기록을 나타내는 데이터프레임을 생성하는 코드입니다. 이 데이터프레임을 사용하여 다음 작업을 수행하세요.

```python

import pandas as pd

# 데이터프레임 생성
data = {
    'ProductID': [101, 102, 103, 104],
    'SaleDate': ['2021-07-01', '2021-07-03', '2021-07-02', '2021-07-04'],
    'Quantity': [3, 2, 5, 4]
}

df = pd.DataFrame(data)
```

- ProductID를 데이터프레임의 인덱스로 설정하세요.
- Quantity를 기준으로 데이터를 내림차순으로 정렬하세요.
- 정렬된 데이터프레임의 인덱스를 기본 인덱스로 재설정하세요.

In [29]:
import pandas as pd

data = {
    'ProductID': [101, 102, 103, 104],
    'SaleDate': ['2021-07-01', '2021-07-03', '2021-07-02', '2021-07-04'],
    'Quantity': [3, 2, 5, 4]
}

df = pd.DataFrame(data)
df

   ProductID    SaleDate  Quantity
0        101  2021-07-01         3
1        102  2021-07-03         2
2        103  2021-07-02         5
3        104  2021-07-04         4

In [30]:
df.set_index('ProductID', inplace=True)
df.sort_values('Quantity', ascending=False, inplace=True)
df

             SaleDate  Quantity
ProductID
103        2021-07-02         5
104        2021-07-04         4
101        2021-07-01         3
102        2021-07-03         2

In [31]:
df.reset_index(inplace=True)
df

   ProductID    SaleDate  Quantity
0        103  2021-07-02         5
1        104  2021-07-04         4
2        101  2021-07-01         3
3        102  2021-07-03         2

---
-  🔒 저작권 및 사용 조건 (중요)
  - **저작권 보호**: 이 강의 노트는 저작권법에 의해 엄격히 보호됩니다.
  - **무단 사용 금지**: 어떠한 형태로든 상업적 사용이 엄격히 금지됩니다.
  - **개인용도 한정**: 이 자료는 교육 목적으로만 사용이 허가되며, 개인적인 학습 외의 목적으로 사용할 수 없습니다.
  - **위반 시 조치**: 저작권법 위반 시 법적 조치가 취해질 수 있습니다.
---

<img src="https://i.ibb.co/sFcTVM4/DALL-E-2023-12-28-17-48-36-Create-a-logo-using-the-simplified-design-featuring-a-sprout-and-an-upwar.png" width="100"/>